### ISSUE TITLE
Site Architecture diagram

### ISSUE THREAD

**Issue by kellychurchill** [ibm-frontend/gatsby-carbon-starter#18]
![screen shot 2019-01-14 at 4 48 18 pm](https://user-images.githubusercontent.com/2744778/51146434-67bb7480-181c-11e9-95d6-ab00408a88a0.png)

**Comment by poofichu** [comment]
Assign me! Wee!

**Comment by poofichu** [comment]
Just kidding! Moving this to somewhere else.
